# Generated by Django 4.2.11 on 2024-05-04 00:49

import core.fields
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(default=None, editable=False, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('finished', 'Finalizado'), ('error', 'Erro')], default='processing', max_length=10)),
                ('file', models.FileField(upload_to='upload')),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Upload Questões',
                'verbose_name_plural': 'Uploads Questões',
                'db_table': 'upload_questions',
            },
        ),
    ]
