# Generated by Django 4.2.11 on 2024-05-05 08:09

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_studentuser'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Enunciado'),
        ),
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(default=None, editable=False, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('in_progress', 'Em Progresso'), ('completed', 'Finalizado')], default='in_progress', max_length=255, verbose_name='Status')),
                ('next_index', models.IntegerField(default=0, verbose_name='Próximo Índice')),
                ('design', models.TextField(blank=True, default=None, null=True, verbose_name='Design')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='learning.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='user.studentuser')),
            ],
            options={
                'verbose_name': 'Avaliação do Usuário',
                'verbose_name_plural': 'Avaliações dos Usuários',
                'db_table': 'user_has_assessments',
            },
        ),
    ]
