# Generated by Django 4.2.11 on 2024-05-17 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_alternative_text_alter_question_statement_and_more'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='QuestionPoolHasQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.questionpool')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.question')),
            ],
            options={
                'verbose_name': 'Questão no Banco de Questões',
                'verbose_name_plural': 'Questões nos Bancos de Questões',
                'db_table': 'question_pool_has_questions',
            },
        ),
        migrations.AlterField(
            model_name='questionpool',
            name='questions',
            field=models.ManyToManyField(related_name='pools', through='learning.QuestionPoolHasQuestion', to='learning.question'),
        ),
    ]
    
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=state_operations,
        ),
    ]
