# Generated by Django 4.2.11 on 2024-05-17 22:41

import core.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_questionpoolhasquestion_alter_questionpool_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpoolhasquestion',
            name='created',
            field=core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='questionpoolhasquestion',
            name='modified',
            field=core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='questionpoolhasquestion',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='questionpoolhasquestion',
            name='removed',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
    ]
