# Generated by Django 4.2.11 on 2024-05-20 00:40

import core.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_questionpoolhasquestion_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MirtDesignData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(default=None, editable=False, null=True)),
                ('item_history', models.JSONField(default=list, verbose_name='Histórico de Itens')),
                ('response_history', models.JSONField(default=list, verbose_name='Histórico de Respostas')),
                ('theta_history', models.JSONField(default=list, verbose_name='Histórico de Theta')),
                ('standard_error_history', models.JSONField(default=list, verbose_name='Histórico de Erro Padrão do Theta')),
                ('user_assessment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='design_data', to='learning.userassessment')),
            ],
            options={
                'verbose_name': 'Dados de Design MIRT',
                'verbose_name_plural': 'Dados de Design MIRT',
                'db_table': 'mirt_design_data',
            },
        ),
    ]
