# Generated by Django 4.2.11 on 2024-09-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_mirtdesigndata'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
