# Generated by Django 4.2.11 on 2024-09-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_assessment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='finished',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Finalizado'),
        ),
    ]
