# Generated by Django 4.2.11 on 2024-09-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_userassessment_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='finish',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fim'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='start',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Início'),
        ),
    ]
