# Generated by Django 4.2.11 on 2024-09-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_assessment_finish_assessment_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSuperPool',
            fields=[
            ],
            options={
                'verbose_name': 'Super Banco de Questões',
                'verbose_name_plural': 'Super Bancos de Questões',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('learning.questionpool',),
        ),
        migrations.AddField(
            model_name='questionpool',
            name='super_pool',
            field=models.BooleanField(default=False, verbose_name='É um Super Pool?'),
        ),
    ]
