# Generated by Django 4.2.11 on 2024-09-20 19:29

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_mirtdesigndata'),
        ('user', '0003_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(default=None, editable=False, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'user_pools',
            },
        ),
        migrations.CreateModel(
            name='UserPoolHasUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(default=None, editable=False, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userpool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário na Turma',
                'verbose_name_plural': 'Usuários nas Turmas',
                'db_table': 'user_pool_has_users',
            },
        ),
        migrations.CreateModel(
            name='UserPoolHasAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', core.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', core.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(default=None, editable=False, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.assessment')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userpool')),
            ],
            options={
                'verbose_name': 'Avaliação da Turma',
                'verbose_name_plural': 'Avaliações das Turmas',
                'db_table': 'user_pool_has_assessments',
            },
        ),
        migrations.AddField(
            model_name='userpool',
            name='assessments',
            field=models.ManyToManyField(related_name='pools', through='user.UserPoolHasAssessment', to='learning.assessment'),
        ),
        migrations.AddField(
            model_name='userpool',
            name='users',
            field=models.ManyToManyField(related_name='pools', through='user.UserPoolHasUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
